bucket/officetoolplus.json

- `checkver` link is set to `https://otp.landian.vip/zh-cn/` because version info on [English homepage](https://otp.landian.vip/en-us/) lags behind.
- Based on my experience, it's fine to assume the full version number ends with `_0` (i.e. `a_b_c_0`), but if you mind I can write a simple API to get that 😃

officetoolplus: init version 6.4.0

---

bucket/officetoolplus.json

Find its GitHub repo, though the version on the website is slightly newer 🤷‍♀️
Reminders:
1. Your branch protection rules are [blocking auto updates](https://github.com/h404bi/dorado/commit/4691cba90562f00f0a6fbae8617f43b61bd3b360/checks#step:4:231)
2. `redis-desktop-manager` [seems to have been moved](https://github.com/h404bi/dorado/commit/4691cba90562f00f0a6fbae8617f43b61bd3b360/checks#step:4:62) to https://github.com/necan/RedisDesktopManager, but its latest version is `0.9.8`, expected `2019.1`

officetoolplus: revise manifest

---

bucket/bamboo.json

Bamboo allows you to use your TinyPNG API key to losslessly compress local PNG/JPG's on your computer.
This json has been successfully installed bamboo on my pc.
```
PS C:\Users\****> scoop install bamboo
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'bamboo' (1.2.0) [64bit]
Loading bamboo-win32-ia32.zip from cache.
Checking hash of bamboo-win32-ia32.zip ... ok.
Extracting bamboo-win32-ia32.zip ... done.
Linking ~\scoop\apps\bamboo\current => ~\scoop\apps\bamboo\1.2.0
Creating shortcut for Bamboo (bamboo.exe)
'bamboo' (1.2.0) was installed successfully!
```

bamboo: Add version 1.2.0

---

bucket/microsoftedge.json

**WIP**
failed in PowerShell 6+, due to https://github.com/PowerShell/PowerShell/issues/2896
```
$ curl -X GET -I https://api.shuax.com/v2/download/edge/stable/x86
HTTP/1.1 307 Temporary Redirect
Server: nginx
Date: Sun, 02 Feb 2020 12:12:50 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Location: http://msedge.f.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/6aadba07-0e75-4d32-9302-217f397442dd?P1=1580731970&P2=402&P3=2&P4=ZLh8MNIdMlAi0b4VoMsUeNr%2bqgB4AXlHbT3%2bzJ%2fkuDNFQi2B%2bJidmzST80ufikrwf0ohJWoLkY0eL86zUaAu4w%3d%3d
Vary: Accept-Encoding
```
Solution: ~~change download API endpoint, or wait for PowerShell updates.~~ https://github.com/lukesampson/scoop/pull/3902
credit: the download endpoint is provided by …

microsoftedge: Add version 83.0.478.61

---

bucket/chunky.json

https://github.com/chawyehsu/dorado/runs/898577390?check_suite_focus=true#step:4:77
1.x seems no longer updating so removing autoupdate is also feasible.

chunky: fix checkver

---

bucket/utools.json

I write [a checkver helper](https://github.com/kidonng/sushi/blob/master/api/utools.ts), basically it prevents updating to old versions.
You can deploy it on your own if you prefer.

utools: use checkver helper

---

bucket/clash-for-windows-portable.json
bucket/clash-for-windows.json

新增了x86支持。
另外作者说这个版本的便携版可能存在问题，预计下个版本修复，并且修改便携版配置文件目录及激活逻辑。

clash-for-windows(-portable): add x86 architecture

---

bucket/clash-for-windows-portable.json

适配新版的文件目录和判断逻辑：
新版本中CFW使用应用目录下的``data``文件夹触发portable mode并存储用户配置

clash-for-windows-portable: adjust for new version

---

bucket/jiduscan.json

添加极度扫描，2.3.0
已经在电脑上测试安装成功
```
scoop install jiduscan
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'jiduscan' (2.3.0) [64bit]
Starting download with aria2 ...
......
Download: Status Legend:
Download: (OK):download completed.
Checking hash of %E6%9E%81%E5%BA%A6%E6%89%AB%E6%8F%8F%202.3.0%20x64%20.7z ... ok.
Extracting %E6%9E%81%E5%BA%A6%E6%89%AB%E6%8F%8F%202.3.0%20x64%20.7z ... done.
Linking ~\scoop\apps\jiduscan\current => ~\scoop\apps\jiduscan\2.3.0
Creating shim for '极度扫描'.
Creating shortcut for 极度扫描 (极度扫描.exe)
'jiduscan' (2.3.0) was installed successfully!
```

jiduscan: Add version 2.3.1

---

bucket/clash-for-windows-portable.json

1. 移除初始化 geoip database 的脚本，保留用户版本
2. 适配 ia32 版本的 installer 脚本 （参考 #239 ）

clash-for-windows-portable: update scripts for x86 version and geoip database

---

bucket/texlive.json

sha512 come from the .sha512 file

texlive: hash fix

---

bucket/steampp.json

steampp: Update to version 2.4.1

---

bucket/picgo.json

[Picgo](https://github.com/Molunerfinn/PicGo) added ia32(x86) version in the recent stable release [build.](https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.0)
The naming rule has changed too! 
[`PicGo-Setup-2.3.0-x64.exe`](https://github.com/Molunerfinn/PicGo/releases/download/v2.3.0/PicGo-Setup-2.3.0-x64.exe) and [`PicGo-Setup-2.3.0-ia32.exe`](https://github.com/Molunerfinn/PicGo/releases/download/v2.3.0/PicGo-Setup-2.3.0-ia32.exe) are the installer files in the release asserts now.
In this pr
-  I added both x86 and x64 versions. 
- Since the hash of the x86 version is not in the [yaml](https://github.com/Molunerfinn/PicGo/releases/download/v2.3.0/latest.yml) file. I left it for scoop to calculate.
- The x64 version used the old way to extract the hash from the yaml file.
By the …

picgo: update picgo download url

---

bucket/texlive.json

The hash of texlive was outdate.

texlive: fix hash

---

bucket/winlibs-mingw-llvm-ucrt.json
bucket/winlibs-mingw-snapshot.json
bucket/winlibs-mingw-ucrt.json
bucket/winlibs-mingw.json

As mentioned here https://github.com/chawyehsu/dorado/pull/439#discussion_r746252730, this pr do a minor fix on winlibs description.
As well as made llvm version be mandatory at the checkver regex configuration of winlibs-mingw-llvm-ucrt.

winlibs-mingw-ucrt: Fix description

---

bucket/miniconda3.json

In the <https://repo.continuum.io/miniconda>, `4.10.3` comes before `4.9.2`
- I modified `checkver` and `autoupdate.url` referring to [extra/miniconda3](https://github.com/ScoopInstaller/Extras/blob/master/bucket/miniconda3.json)
- Default channels point to `repo.anaconda.com` instead of `repo.continuum.io`
https://github.com/conda/conda/issues/6886

miniconda3: Update to version 4.10.3

---

bucket/qbittorrent-enhanced.json

An issue that may be discussed is that the new version releases the Qt5 and Qt6 versions for x64. I don't know whether it will release like this in further versions. So I didn't change the URL in autoupdate.

qbittorrent-enhanced: Update to version 4.4.1.10

---

bucket/snipaste-beta.json

- fix error while unintalling `snipaste-beta`
``` powershell
Uninstalling 'snipaste-beta' (2.7.3-Beta).
Running uninstaller script...
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Snipaste.lnk
Unlinking ~\scoop\apps\snipaste-beta\current
Get-Item : 找不到路径“C:\Users\Akariiin\scoop\apps\snipaste-beta\2.7.3-Beta\config.ini”，因为该路径不存在。
所在位置 C:\Users\Akariiin\scoop\apps\scoop\current\lib\install.ps1:1216 字符: 23
+             $source = Get-Item "$dir\$source"
+                       ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\Akarii...Beta\config.ini:String) [Get-Item], ItemNotFoundExcep
tion
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
'snipaste-beta' was uninstalled.
```
- persist …

snipaste-beta: fix backup file error

---

bucket/unityhub.json

When click sign in, the unity hub will open the default browser to login and bring up the unity hub to complete the login.

unityhub: Add `post_install` to resolve login failure

---

bucket/swift.json

Swift moved to `libicu69` in the latest versions, so `env_add_path` needed an update.

swift: update to libicu69

---

bucket/anaconda3.json
bucket/miniconda3.json

Add additional note for user to run 'conda activate base', otherwise running 'conda create' will not work.
For people just want to run some app like myself, this will help a lot.

conda3: Update notes

---

bucket/clash-for-windows-np.json
bucket/clash-for-windows.json
bucket/crystaldiskinfo-shizuku-edition.json
bucket/crystaldiskmark-shizuku-edition.json

For `clash-for-windows`:
- Add support for arm64
For `clash-for-windows-np`:
- Add support for arm64
For `crystaldiskinfo-shizuku-edition`:
- Add support for arm64
For `crystaldiskmark-shizuku-edition`:
- Add support for arm64
- Drop support for arm32

crystaldisk* apps | clash for windows(-np): add arm64 architecture

---

bucket/downkyi.json

[v1.5.8 release page](https://github.com/leiurayer/downkyi/releases/tag/v1.5.8)

downkyi: fix download url error

---

bucket/clash-for-windows-np.json
bucket/clash-for-windows.json

clash-for-windows: installer from exe format to 7z format

---

bucket/dandanplay.json

In latest version, one more folder named `WebView2` would be extracted from installer, and cause following error:
```powershell
Running installer script...
Could not find 'BDC5719 WebView2'! (error 16)
At C:\Users\A1\scoop\apps\scoop\current\lib\core.ps1:638 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Could not find ...w2'! (error 16):String) [], RuntimeException
+ FullyQualifiedErrorId : Could not find 'BDC5719 WebView2'! (error 16)
```
Exclude this folder in `Get-ChildItem` would fix the error.

dandanplay: Fix error when running installer script

---

bucket/qqnt.json

Update `checkver` and `autoupdate` to support new URL format.
Build number is replaced by build date in URL and became invisible in page

qqnt: Update checkver and autoupdate

---

bucket/kdeconnect.json

KDE binary factory has migrated to KDE's GitLab. See details:
https://blogs.kde.org/2024/01/30/farewell-binary-factory-add-craft-jobs-your-apps-kdes-gitlab-now/
related: https://github.com/ScoopInstaller/Extras/issues/12897

kdeconnect: Fix checkver

---

bucket/imewlconverter.json

The previous manifest incorrectly attempted to link a shortcut that did not exist in the expected directory. This change updates the 'extract_dir' to ensure that the contents of the 'publish' directory within the zip file are correctly extracted to the 'imewlconverter' directory, allowing for the shortcut to be properly created.

imewlconverter: Fix extract_dir

---

bucket/msys2-cn.json

The Ruby Installerrelies on the `scoop prefix msys2` command to ascertain whether MSYS2 has been installed via Scoop. This detection method, however, fails to recognize the variant named `msys2-cn` in this bucket, leading to unsuccessful detection. Consequently, despite MSYS2 being installed, the installer cannot locate it and erroneously concludes that "MSYS2 seems to be unavailable."
https://github.com/oneclick/rubyinstaller2/blob/ff06a60e42f98807b2d1329d6774cf6c72074157/lib/ruby_installer/build/msys2_installation.rb#L48-L104
The modification is to add an environment variable so that the installer can recognize msys2-cn in `MSYS2_PATH`.

msys2-cn@20241208: fix cannot be recognized by ridk

---

bucket/neteasemusic.json

checkver logs:
```powershell
neteasemusic: 3.1.3.203419 (scoop version is 3.1.1.203306) autoupdate available
Autoupdating neteasemusic
DEBUG[1737737900] [$updatedProperties] = [url hash] -> ~\scoop\apps\scoop\current\lib\autoupdate.ps1:478:5
DEBUG[1737737900] $substitutions (hashtable) -> ~\scoop\apps\scoop\current\lib\autoupdate.ps1:216:5
DEBUG[1737737900] $substitutions.$dotVersion                    3.1.3.203419
DEBUG[1737737900] $substitutions.$matchTail                     .203419
DEBUG[1737737900] $substitutions.$basenameNoExt                 NeteaseCloudMusic_Music_official_3.1.3.203419_32
DEBUG[1737737900] $substitutions.$patchVersion                  3
DEBUG[1737737900] $substitutions.$match1                        3.1.3.203419
DEBUG[1737737900] $substitutions.$urlNoExt …
```

neteasemusic: Update to version 3.1.3.203419

---

bucket/utools.json

checkver logs:
```powershell
utools: 6.1.0 (scoop version is 5.1.0) autoupdate available
Autoupdating utools
DEBUG[1737735949] [$updatedProperties] = [url hash] -> ~\scoop\apps\scoop\current\lib\autoupdate.ps1:478:5
DEBUG[1737735949] $substitutions (hashtable) -> ~\scoop\apps\scoop\current\lib\autoupdate.ps1:216:5      
DEBUG[1737735949] $substitutions.$basename                      uTools-6.1.0-ia32.exe
DEBUG[1737735949] $substitutions.$version                       6.1.0
DEBUG[1737735949] $substitutions.$matchHead                     6.1.0
DEBUG[1737735949] $substitutions.$dashVersion                   6-1-0
DEBUG[1737735949] $substitutions.$dotVersion                    6.1.0
DEBUG[1737735949] $substitutions.$baseurl                       https://open.u-tools.cn/download …
```

utools: Update to version 6.1.0 (close #934)
