chawyehsu/dorado

bucket/neteasemusic.json
Don't know why they removed the underscore 😂
=> neteasemusic: fix download link

bucket/neteasemusic.json
=> neteasemusic: fix download url

bucket/pandownload.json
I intended to do this together with #15 but forgot, sorry to bother you 😃
=> pandownload: persist data

bucket/fu.json
=> fu: Update to version 2.0.0

bucket/ediary.json
[ediary](http://www.haoxg.net/ediary/index.html) 是一个有20年历史的日记本，广受好评。
=> ediary: Add version 3.3.7

bucket/copytranslator.json
First time pr for scoop bucket, please check twice😂
=> copytranslator: Add version 9.0.0

bucket/qtscrcpy.json
https://github.com/barry-ran/QtScrcpy
https://blog.csdn.net/rankun1/article/details/87970523
=> qtscrcpy: Add version 1.3.0

bucket/firefox-nightly-zh-cn.json
Add Firefox Nightly chinese(simplified) version.
=> Add manifest firefox-nightly-zh-cn

bucket/neteaseuu.json, bucket/yy.json
=> Add neteaseuu yy manifests

bucket/qbittorrent-enhanced.json
Update x64 version to v4.2.5.12, while x86 version is v4.2.5.11.
=> qbittorrent-enhanced: update to version 4.2.5.12

bucket/crystaldiskinfo-shizuku-edition.json, bucket/crystaldiskmark-shizuku-edition.json
为CrystalDiskInfo和CrystalDiskMark注入灵魂XD
参照了extras仓库的[CrystalDiskInfo脚本](https://github.com/lukesampson/scoop-extras/blob/master/bucket/crystaldiskinfo.json)和[CrystalDiskMark脚本](https://github.com/lukesampson/scoop-extras/blob/master/bucket/crystaldiskmark.json)，由于是第一次写Manifest，如果发现有错误希望可以指出🙏
=> Add: CrystalDiskInfo Shizuku Edition and CrystalDiskMark Shizuku Edition

bucket/scrcpy-gui.json
close https://github.com/chawyehsu/dorado/issues/124
=> scrcpy-gui: Add version 1.5.1

bucket/clashweb.json
=> clashweb: fix hash

bucket/qbittorrent-enhanced.json
=> qbittorrent-enhanced: delete notes field

bucket/crystaldiskinfo-shizuku-edition.json, bucket/crystaldiskmark-shizuku-edition.json
第一次写的时候没注意正反斜杠，虽然他work但总觉得怪难受的_(:з」∠)_
=> crystaldisk*: polish manifest

bucket/autodarkmode.json
=> autodarkmode: fix install script

bucket/llvm-mingw.json
hi, i updated url about llvm-mingw，please check it out
=> llvm-mingw: Update to version 20201020

bucket/mubu.json
更新data路径描述，当前版本`Mubu`文件夹位于`%APPDATA%`目录
=> Edit note content for Mubu

bucket/lemon.json
https://github.com/iotang/Project_LemonLime
=> lemon: Add version 0.2.7

bucket/yesplaymusic.json
[YesPlayMusic](https://github.com/qier222/YesPlayMusic)是网易云音乐的第三方客户端。我已经在我的电脑（Windows 10专业版 20H2 19042.804 Windows Feature Experience Pack 120.2212.551.0）上测试过了，可以正常运行。我看不懂 Installer 的 bucket 配置方式，所以我提交了一个便携版的 manifest。如果可以的话，希望能帮忙提交一下安装版的 manifest，谢谢！
=> yesplaymusic: Add version 0.3.3

bucket/another-redis-desktop-manager.json
=> another-redis-desktop-manager: Add version 1.4.0

bucket/yesplaymusic.json
将 `yesplaymusic` 更新到`0.3.5`版本，将原来的连接应用名与版本号的`.`修改为`-`
close #299
=> yesplaymusic: Update to version 0.3.5 and Change its naming pattern

bucket/qbittorrent-enhanced.json
=> qbittorrent-enhanced: persist profile

bucket/siyuan.json
=> siyuan: Update to version 1.1.83

bucket/clashweb.json
- profile:保存配置文件
- api/currentmode.py:保存代理模式
- App/tmp.vbs:保存选中的配置文件
=> clashweb: persist profile

bucket/kdeconnect.json
Close https://github.com/chawyehsu/dorado/issues/287
=> kdeconnect: Add version 1.4-574

README.md
This sounds slightly better. Accept or reject as you see fit.
=> docs: Grammar tweak in readme

bucket/trafficmonitor.json
=> trafficmonitor: Update to version 1.80

bucket/dingtalk.json
=> dingtalk: Update to version 6.0.15.5080287 

README.md, README.zh-Hans.md, bucket/winlibs-mingw-llvm-ucrt.json, bucket/winlibs-mingw-ucrt.json
I'm not sure about how scoop repo works, but I tried and this file do work for me.
=> winlibs-mingw-ucrt: Add version 11.2.0-13.0.0-9.0.0-ucrt-r2

bucket/imewlconverter.json
=> imewlconverter: Add version 2.9.0

bucket/downkyi.json
哔哩下载姬downkyi，B站视频下载工具，支持批量下载，支持4K，支持解除地区限制下载，提供工具箱（音视频提取、去水印等）。
=> downkyi: Add version 1.4.0

bucket/steampp.json
Add AppData to persist folder so that configs won't be lost during upgrading.
=> steampp: Persist appdata

bucket/clash-for-windows-np.json, bucket/clash-for-windows.json
Path of app uninstaller has been changed in latest version.
=> clash-for-windows: update uninstaller file path

bucket/clash-verge.json
clash-verge is a Clash GUI based on tauri.
=> clash-verge: Add version 1.0.1

bucket/utools.json
=> utools: update post_install scripts

bucket/bbdown.json
=> bbdown: Update to version 1.5.3

bucket/pstools.json
- Add alias shim for 64bit version
- Add `checkver` and `autoupdate`
=> PsTools: Add alias shim, checkver and autoupdate

bucket/mosdns-cn.json, bucket/mosdns.json
Add [mosdns](https://github.com/IrineSistiana/mosdns).
=> mosdns: Add version 3.9.0

bucket/kdeconnect.json
=> kdeconnect: Fix checkver

bucket/officetoolplus.json
* Add 32bit architecture
* Fix 'checkver'
* Fix 'autoupdate'
=> officetoolplus: Update to version 10.1.7.0

bucket/clipber.json
=> clipber: Update checkver

bucket/bilibili.json
The previous link had a problem with reuse the cache.
=> bilibili: Update checkver

bucket/bilibili.json
persist bilibili data into Scoop's local folder
=> bilibili: Update persist

bucket/frpmgr.json
=> frpmgr: Add version 1.12.0

bucket/neteasemusic.json
=> neteasemusic: Update to version 2.10.10.201297_32

bucket/crystaldiskinfo-shizuku-edition.json, bucket/crystaldiskmark-shizuku-edition.json
The release page and download site has been changed.
=> crystaldisk(*): Update URLs

bucket/capcut.json
=> capcut: Update to version 2.4.0.634

bucket/lxmusic.json
a free & open source music finder
=> lxmusic: Add version 2.3.0

bucket/autodarkmode.json
=> autodarkmode@10.4.0.35: fix extract_dir

bucket/dandanplay.json
- Remove residual field `extract_dir`
- Remove repeated space
=> Dandanplay: polishes

bucket/crystaldiskmark-aoi-edition.json
- Update to version 8.0.5
- Fix regexp not working in `checkver`
- Update source URL in `autoupdate`
- Add aoi edition
=> crystaldiskmark(*): Update shizuku edition, add aoi edition

bucket/plain-craft-launcher.json
=> plain-craft-launcher: Add version 2.7.1

bucket/qqnt.json
=> qqnt: Update checkver

bucket/neteaseuu.json
close https://github.com/chawyehsu/dorado/issues/896
=> neteaseuu: fix shortcut

README.md, README.zh-Hans.md
Commit c9b0eec9626a332e6aa4214fc1b67a4eb5a7fec2 renamed `LICENSE` to `UNLICENSE`. This PR adjusts sources to changes.
=> fix: update license reference

bucket/qqmusic.json
=> qqmusic@21.31: Persist Plugins

bucket/neteaseuu.json
=> neteaseuu: Update to version 5.42.1.5077

bucket/texlive.json
There is a change in texlive 2024, which involves modifying the bin path .
Similar as [#701](https://github.com/chawyehsu/dorado/pull/701).
=> texlive: Update bin path

bucket/dandanplay.json
Use [dandanplay Github repo](https://github.com/kaedei/dandanplay) for checkver and autoupdate
=> dandanplay: Update checkver and download url

bucket/cloudflare-speedtest.json
=> cloudflare-speedtest: Add version 2.2.5
